export const NamesEnglish: {[key:string]: string} = {
    NewPassword: 'New Password',
    ConfirmNewPassword :'Confirm New Password',
    ResetMyPassword : 'Reset My Password',
    EmailAddress: 'Email Address',
    ForgotPassword: "Forgot Password?",
    Password: "Password",
    SignIn: "Sign In",
    SignOut: "Sign Out",
    SignUp: "Sign Up",
    CreateAccount: "Create an Accoun",
    CorrectAccount: "Correct an Account",
    AlreadyHaveAccount: "Already have an Account?",
    DisplayName: "Display Name",
    ConfirmPassword: "Confirm Password",
    SignMeUp: "Sign me Up ",
    DoYouWantCorrectAccount: "Do you want to correct an account?",
    PleaseSpecifyYourCurrentPassword: "Please, specify your Current Password!",
    PasswordsDoNotMatch: 'Passwords do not match!',
    PleaseSpecifyNewPassword: 'Please, specify New Password!',
    UserProfile: 'User Profile',
    EMail: 'E-Mail',
    FullName: 'Full Name',
    Address: 'Address',
    DeleteMyProfile: 'Delete My Profile',
    DeletingYourProfile: "Deleting your profile you will not be able to Start Trails and all your trails will be deactivated",
    Save: "Save",
    AreYouSureYouWantDeleteProfile: 'Are you sure you want to delete your profile?',
    YouWillNotBeAbleToStartTrails: 'You will not be able to Start Trails and all your trails will be deactivated.',
    ChangePassword: 'Change Password:',
    CurrentPassword: 'Current Password',
    TheAdminPageIsAccessible: 'The Admin Page is accessible by every signed in admin user.',
    Username: "Username",
    Role: "Role",
    Details: "Details",
    ID: "ID",
    Admin: "Admin",
    SuperAdministrator: "Super Administrator",
    ADMIN: "Administrator",
    EDITOR: 'Trails Editor',
    USER: 'Registered User',
    SUPERADMIN: 'Super Administrator',
    INACTIVE: 'Inactive User',
    Trails: "Trails",
    MyThoughts: 'My Thoughts',
    AddNew: 'Add New',
    CopyClipboard: 'Copy to Clipboard',
    Download: "Download",
    SaveAs: "Save as",
    LastUpdated: 'Last Updated',
    Delete: "Delete",
    Home: "Home",
    Roles: "Roles",
    Contacts: "Contacts",
    AddTrail: 'Add Trail',
    Profile: "Profile",
    AdminShort: "Admin",
    TrailsReport: 'Trails Report',
    MyTrails: 'My Trails',
    MyRunningTrails: 'My Running Trails',
    EditStepItem: "Edit step item",
    AddStepItem: "Add step item",
    PleaseSelectItemType: 'Please select item type',
    question: "question",
    description: "description",
    text: "text",
    picture: "picture",
    Location: "Location",
    left: "left",
    right: "right",
    center: "center",
    flow: "flow",
    YouAreCurrently: "You are currently in a state: Inactive User",
    PleaseContact: " Please contact Admin to change your role.",
    GoToTrailDetails: "Go to Trail Details",
    Question: "Question",
    Answer: "Answer",
    PleaseAnswerQuestion: "Please answer the question",
    FinishedOn: "Finished on",
    LastVisited : "Last Visited",
    TrailActivity : "Trail Activity",
    Area: "Area",
    Subject : "Subject",
    Author  : "Author",
    City : "City",
    Passed  : "Passed",
    Steps: "Steps",
    Step: "Step",
    StartContinue: "Start/Continue",
    EditTrail: "Edit Trail",
    RemoveTrail  : "Remove Trail",
    CopyTrail  : "Copy Trail",
    ResetTrail : "Reset Trail",
    ShowMyAnswers : "Show My Answers",
    DoYouWantRemoveTrail: "Do you want to remove trail?",
    DoYouWantResetTrail: "Do you want to reset trail?",
    AfterRESET : "After RESET this trail all your answers will be deleted!",
    Description: "Description",
    ShortDescription: "Short Description",
    FinishTrail: "Finish trail",
    StepDone: "Step done, go to the next", 
    GoToCurrentStep: "Go to the current step",
    SaveChanges: "Save changes",
    TrailFinished: "Trail finished",
    ThereAreUnsavedChanges: "There are unsaved changes on the step.",
    DoYouWantSaveThem : "Do you want to save  them",
    of: "of",
    CurrentIs: "Current is",
    AddStep: "Add Step",
    MoveStepBack: "Move step back",
    MoveStepForward: "Move step forward",
    RemoveStep: "Remove step",
    NoSteps: "No steps",
    StopPreview: "Stop Preview",
    StartPreview: "Start Preview",
    Text: "Text",
    Picture: "Picture",
    PictureText: "Picture text",
    MoveStepItemDown  : "'Move Step Item Down",
    MoveStepItemUp: "Move Step Item Up",
    SetStepPosition: "Set step position",
    Preview: "Preview",
    DoYouWantRemoveStep: "Do you want to remove step?",
    RemoveStepItem: "Remove step item",
    DoYouWantRemoveStepItem: 'Do you want to remove step item?',
    TrailTitle: "Trail Title",
    titleArea: 'Bitte hier den Bereich eingeben, für welchen dieser Trail gedacht ist, beispielsweise: Firma, Schule, Coaching, Ausbildung, Familie, Partnerschaft, Umweltschutz, Menschenrechte, ...\n' +
        ' Please enter the area for which this trail is intended, for example: company, school, coaching, training, family, partnership, environmental protection, human rights, ....',
    titleSubject: 'Bitte hier das Themengebiet eingeben, beispielsweise: Teamentwicklung, Zusammenarbeit, Ferien, Beziehung, Zero Waste, Energiesparen, Konflikte, ...\n' +
        'Please enter the topic here, for example: team development, cooperation, holidays, relationships, zero waste, energy saving, conflicts, ...',
    titleCategory: 'Bitte hier die Kategorie eingeben, beispielsweise: zukunftsweisend, problemlösend, stärkend, verbessernd, beste Hoffnung...\n ' +
        'Please enter the category here, for example: future - oriented, problem - solving, strengthening, improving, best hope',
    Public: 'Public',
    Active: 'Active',
    Category: 'Category',
    CreatedAt: "Created at",
    LastEditedAt: 'Last edited at',
    User: 'User',
    CountSteps: ' Count of Steps',
    PassedStep: 'Passed Step',
    StepLastUpdated: 'Step Last Updated',
    Users: "Users",
    AddNewTrail: "Add New Trail",
    More: 'More',
    DontHaveAnAccount: "Don't have an account?",
    EmailVerification: 'Email Verification',
    EmailConfirmationSent: 'E-Mail confirmation sent: Check you E-Mails(Spam folder included) for a confirmation E-Mail. Refresh this page once you confirmed your E-Mail.',
    VerifyYourEmail: 'Verify your E-Mail: Check you E-Mails (Spam folder included) for a confirmation E- Mail or send another confirmation E-Mail.',
    SendConfirmationEmail: "Send confirmation E-Mail",
    Width: "Width(%)",
    Min: "Min(px)",
    OK: "OK",
    Cancel: "Cancel",
    Yes: "Yes",
    No: "No",
    GoToStep: "Go to step",
    RemoveTrailAnswers: "Remove trail answers",
    MarkAsImportant: "Mark as important",
}; 
