export const NamesGerman: {[key:string]: string} = {
    NewPassword: 'Neues Passwort',
    ConfirmNewPassword :'Neues Passwort bestätigen',
    ResetMyPassword : 'Passwort zurücksetzen',
    EmailAddress: 'Mail Adresse',
    ForgotPassword: "Passwort vergessen?",
    Password: "Passwort",
    SignIn: "Anmelden",
    SignOut: "Abmelden",
    SignUp: "Registrieren",
    CreateAccount: "Neues Benutzerkonto erstellen",
    CorrectAccount: "Benutzerkonto anpassens",
    AlreadyHaveAccount: "Benutzerkonto bereits vorhanden?",
    DisplayName: "Anzeige-Name",
    ConfirmPassword: "Passwort bestätigen",
    SignMeUp: "Melde mich an",
    DoYouWantCorrectAccount: "Benutzerkonto anpassen?",
    PleaseSpecifyYourCurrentPassword: "Bitte aktuelles Passwort angeben!",
    PasswordsDoNotMatch: 'Passwort stimmt nicht überein!',
    PleaseSpecifyNewPassword: 'Bitte neues Passwort eingeben!',
    UserProfile: 'Benutzerprofil',
    EMail: 'Mail',
    FullName: 'Name',
    Address: 'Adresse',
    DeleteMyProfile: 'Mein Profil löschen',
    DeletingYourProfile: "Wenn das Profil gelöscht wird, sind keine Trails mehr startbar und die eigenen Trails werden deaktiviert.",
    Save: "Sichern",
    AreYouSureYouWantDeleteProfile: 'Profil wirklich löschen?',
    YouWillNotBeAbleToStartTrails: 'Keine Trails werden mehr startbar sein und die eigenen Trails werden deaktiviert.',
    ChangePassword: 'Passwort ändern:',
    CurrentPassword: 'Aktuelles Passwort',
    TheAdminPageIsAccessible: 'Admin-Seite nur für Administrator*innen erreichbar.',
    Username: "Benutzername",
    Role: "Rolle",
    Details: "Details",
    ID: "ID",
    Admin: "Admin",
    SuperAdministrator: "Super Administrator",
    ADMIN: "Administrator",
    EDITOR: 'Trails Editor*in',
    USER: 'Registrierte*r Benutzer*in',
    SUPERADMIN: 'Super Administrator*in',
    INACTIVE: 'Inaktive*r User*in',
    Trails: "Trails",
    MyThoughts: 'Meine Gedanken',
    AddNew: 'Neu hinzufügen',
    CopyClipboard: 'In Zwischenablage kopieren',
    Download: "Herunterladen",
    SaveAs: "Sichern unter",
    LastUpdated: 'Letzte Anpassung',
    Delete: "Löschen",
    Home: "Startseite",
    Roles: "Rollen",
    Contacts: "Kontakte",
    AddTrail: 'Trail hinzufügen',
    Profile: "Profile",
    AdminShort: "Admin",
    TrailsReport: 'Trail Bericht',
    MyTrails: 'Meine Trails',
    MyRunningTrails: 'Meine laufenden Trails',
    EditStepItem: "Element anpassen",
    AddStepItem: "Element hinzufügen",
    PleaseSelectItemType: 'Bitte den Element-Typ wählen',
    question: "Frage",
    description: "Zusatzbeschreibung",
    text: "Text",
    picture: "Bild",
    Location: "Ort",
    left: "links",
    right: "rechts",
    center: "zentriert",
    flow: "nebeneinander",
    YouAreCurrently: "Benutzerstatus inaktiviert!",
    PleaseContact: "Bitte den Administrator kontaktieren.",
    GoToTrailDetails: "Gehe zur Trail-Hauptseite ",
    Question: "Frage",
    Answer: "Antwort",
    PleaseAnswerQuestion: "Bitte die Frage beantworten",
    FinishedOn: "Fertiggestellt am",
    LastVisited : "Zuletzt besucht",
    TrailActivity : "Trail Aktivitäten",
    Area: "Bereich",
    Subject : "Themengebiet",
    Author  : "Autor",
    City : "Stadt/Ortschaft",
    Passed  : "durchlaufen",
    Steps: "Schritte",
    Step: "Schritt",
    StartContinue: "Start/Weiterfahren",
    EditTrail: "Trail anpassen",
    RemoveTrail  : "Trail löschen",
    CopyTrail  : "Trail kopieren",
    ResetTrail : "Trail zurücksetzen",
    ShowMyAnswers : "Zeige meine Antworten",
    DoYouWantRemoveTrail: "Trail löschen?",
    DoYouWantResetTrail: "Trail zurücksetzen?",
    AfterRESET : "Nach RESET werden alle Antworten gelöscht!",
    Description: "Beschreibung",
    ShortDescription: "Kurzbeschreibung",
    FinishTrail: "Trail beenden?",
    StepDone: "Schritt fertig, zum nächsten Schritt", 
    GoToCurrentStep: "Gehe zum aktuellen Schritt",
    SaveChanges: "Anpassungen sichern",
    TrailFinished: "Trail beendet",
    ThereAreUnsavedChanges: "Die Anpassungen sind nicht gesichert.",
    DoYouWantSaveThem : "Anpassungen sichern?",
    of: "von",
    CurrentIs: "Aktuell ist",
    AddStep: "Schritt hinzufügen",
    MoveStepBack: "Schritt zurück",
    MoveStepForward: "Schritt vorwärts",
    RemoveStep: "Schritt löschen",
    NoSteps: "Keine Schritte",
    StopPreview: "Stop Vorschau",
    StartPreview: "Start Vorschau",
    Text: "Text",
    Picture: "Bild",
    PictureText: "Bildtext",
    MoveStepItemDown  : "Element nach unten verschieben",
    MoveStepItemUp: "Element nach oben verschieben",
    SetStepPosition: "Schrittposition setzen",
    Preview: "Vorschau",
    DoYouWantRemoveStep: "Schritt löschen?",
    RemoveStepItem: "Element löschen",
    DoYouWantRemoveStepItem: 'Element wirklich löschen?',
    TrailTitle: "Trail Titel",
    titleArea: 'Bitte hier den Bereich eingeben, für welchen dieser Trail gedacht ist, beispielsweise: Firma, Schule, Coaching, Bildung, Ausbildung, Familie, Partnerschaft, Umweltschutz, Menschenrechte, ...\n' +
        ' Please enter the area for which this trail is intended, for example: company, school, coaching, training, family, partnership, environmental protection, human rights, ....',
    titleSubject: 'Bitte hier das Themengebiet eingeben, beispielsweise: Teamentwicklung, Zusammenarbeit, Ferien, Beziehung, Zero Waste, Energiesparen, Konflikte, ...\n' +
        'Please enter the topic here, for example: team development, cooperation, holidays, relationships, zero waste, energy saving, conflicts, ...',
    titleCategory: 'Bitte hier die Kategorie eingeben, beispielsweise: zukunftsweisend, problemlösend, stärkend, verbessernd, beste Hoffnung...\n ' +
        'Please enter the category here, for example: future - oriented, problem - solving, strengthening, improving, best hope',
    Public: 'öffentlich',
    Active: 'aktiv',
    Category: 'Kategorie',
    CreatedAt: "Erstellt am",
    LastEditedAt: 'Zuletzt geändert am',
    User: 'Benutzer',
    CountSteps: ' Anzahl Schritte',
    PassedStep: 'Durchlaufene Schritte',
    StepLastUpdated: 'Schritte zuletzt geändert',
    Users: "Benutzer",
    AddNewTrail: "Trail hinzufügen",
    More: 'Mehr',
    DontHaveAnAccount: "Don't have an account?",
    EmailVerification: 'Email Verification',
    EmailConfirmationSent: 'E-Mail confirmation sent: Check you E-Mails(Spam folder included) for a confirmation E-Mail. Refresh this page once you confirmed your E-Mail.',
    VerifyYourEmail: 'Verify your E-Mail: Check you E-Mails (Spam folder included) for a confirmation E- Mail or send another confirmation E-Mail.',
    SendConfirmationEmail: "Send confirmation E-Mail",
    Width: "Width(%)",
    Min: "Min(px)",
    OK: "OK",
    Cancel: "Cancel",
    Yes: "Yes",
    No: "No",
    GoToStep: "Go to step",
    RemoveTrailAnswers: "Remove trail answers",
    MarkAsImportant: "Mark as important",
}; 
